#!/usr/bin/env bash
#Install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chmod -R 755 /var/www
sudo echo "Hello World!" > /var/www/html/index.html
# check if number of lines returned from  'nginx running process' queried (with the c flag - for line count) is less than or equals 0, then start nginx server otherwise restart the already running server.
if ["$(pgrep -c nginx)" -le 0]; then
	service nginx start
else
	service nginx restart
fi
