#!/usr/bin/env bash
# Create custom 404 page
INDEX_COPY="Hello World!"
ERROR_COPY="Ceci n'est pas une page - 404"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "$INDEX_COPY" > /var/www/html/index.nginx-debian.html
echo "$ERROR_COPY" | sudo tee /var/www/html/custom_404.html > /dev/null
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/^\slocation.*/i \        error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
if ["$(pgrep -c nginx)" -le 0]; then
	service nginx start
else
	service nginx restart
fi
